CariTakip_30.05.2017/CariTakip/ViewModels/Musteriler.cs
using CariTakip.InfraStructure;
using CariTakip.Models;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace CariTakip.ViewModels
{
    public class MusterilerIndex
    {

        public IEnumerable<Musteri> Musteriler { get; set; }
  
    }
    public class MusterilerYeni
    {
        
        [MaxLength(11)]
        [MinLength(11)]
        [RegularExpression("([1-9][0-9]*)", ErrorMessage = "Lütfen Tc alanına sadece rakamla yazınız.")]
        public string Tc { get; set; }
        [MaxLength(10)]
        [MinLength(10)]
        [RegularExpression("([1-9][0-9]*)", ErrorMessage = "Lütfen VergiNo alanına sadece harfle yazınız.")]
        public string VergiNo { get; set; }
        [MaxLength(50)]
      
        public string Ad { get; set; }
        [MaxLength(50)]

        public string Soyad { get; set; }
        [MaxLength(256)]
       
        public string FirmaAdi { get; set; }
       
        [RegularExpression("([1-9][0-9]*)", ErrorMessage = "Lütfen Telefon alanına sadece rakamla yazınız.")] 
        [DataType(DataType.PhoneNumber)]
        [MaxLength(10)]
        [MinLength(10)]
        public string Tel { get; set; }
        [MaxLength(100)]
  
        [DataType(DataType.EmailAddress)]
        public string Email { get; set; }
        public string Adres { get; set; }
    

    }
    public class MusterilerDuzenle
    {
        [MaxLength(11)]
        [MinLength(11)]
        [RegularExpression("([1-9][0-9]*)", ErrorMessage = "Lütfen Tc alanına sadece rakamla yazınız.")]
        public string Tc { get; set; }
        [MaxLength(10)]
        [MinLength(10)]
        [RegularExpression("([1-9][0-9]*)", ErrorMessage = "Lütfen VergiNo alanına sadece harfle yazınız.")]
        public string VergiNo { get; set; }
        [MaxLength(50)]
   
        public string Ad { get; set; }
        [MaxLength(50)]
       
        public string Soyad { get; set; }
        [MaxLength(256)]
        public string FirmaAdi { get; set; }
        [RegularExpression("([1-9][0-9]*)", ErrorMessage = "Lütfen Telefon alanına sadece rakamla yazınız.")]
        [DataType(DataType.PhoneNumber)]
        [MaxLength(10)]
        [MinLength(10)]
        public string Tel { get; set; }
        [MaxLength(100)]

        [DataType(DataType.EmailAddress)]
        public string Email { get; set; }

        public string Adres { get; set; }
        
     

    }

    public class KasaIndex
    {

        public PagedData<CariHesap> CariHesap { get; set; }
        public double GirenMiktar { get; set; }
        public double CikanMiktar { get; set; }
        public double KalanMiktar { get; set; }
        public int MusteriID { get; set; }
        public string MusteriAdi { get; set; }
        public string MusteriSoyadi { get; set; }
    
        public IEnumerable<CariHesap> CariHesaplar { get; set; }
    }
    public class KasaYeni
    {
    
        [DataType(DataType.DateTime)]
        [Required]
        public DateTime Tarih { get; set; }
         [Required]
        public string Aciklama { get; set; }

        [Required]
        public double GirilenMiktar { get; set; }
        [Required]
        public double CikanMiktar { get; set; }

        public int MusteriID { get; set; }
        public string MusteriAdi { get; set; }
        public string MusteriSoyadi { get; set; }
    
    }
    public class KasaDuzenle
    {
        [DataType(DataType.DateTime)]
        [Required]
        public DateTime Tarih { get; set; }
        [Required]
        public string Aciklama { get; set; }

        [Required]
        public double GirilenMiktar { get; set; }
        [Required]
        public double CikanMiktar { get; set; }
        public string MusteriAdi { get; set; }
        public string MusteriSoyadi { get; set; }
        public int MusteriID { get; set; }


    }
}

CariTakip_30.05.2017/CariTakip/Controllers/MusterilerController.cs
using CariTakip.Models;
using CariTakip.ViewModels;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using NHibernate.Linq;
using System.Web.UI.WebControls;
using System.IO;
using System.Web.UI;
using CariTakip.InfraStructure;
namespace CariTakip.Controllers
{
       [Authorize(Roles = "Admin,Guest")]
    
       [SelectedTabAttribute("musteriler")]
    public class MusterilerController : Controller
    { 
        public ActionResult Index(string SecilenArama,string arama)
        {

            var musteriler = Database.Session.Query<Musteri>().OrderByDescending(x=>x.Id);
         
            if (!String.IsNullOrEmpty(arama))
            {
                if (SecilenArama == "Ad")
                {
                    musteriler = Database.Session.Query<Musteri>().Where(x => x.Ad.Contains(arama)).OrderByDescending(x => x.Id);
                }
                else if (SecilenArama == "FirmaAd")
                {
                    musteriler = Database.Session.Query<Musteri>().Where(x => x.FirmaAdi.Contains(arama)).OrderByDescending(x => x.Id); ;
                }
                else if (SecilenArama == "TcNo")
                {
                    musteriler = Database.Session.Query<Musteri>().Where(x => x.Tc.StartsWith(arama)).OrderByDescending(x => x.Id); ;
                }
                else if (SecilenArama == "VergiNo")
                {
                    musteriler = Database.Session.Query<Musteri>().Where(x => x.VergiNo.StartsWith(arama)).OrderByDescending(x => x.Id); ;
                } 
            }
                   
            return View(new MusterilerIndex() 
              {
                  Musteriler=musteriler
              }
            );
        }
        public ActionResult SahisYeni()
        {
            return View(new MusterilerYeni() { });
        }
        [HttpPost]
        public ActionResult SahisYeni(MusterilerYeni form)
        {

            if (!ModelState.IsValid)
            {
                return View(form);
            }
            var Musteri = new Musteri()
            {
                Tc=form.Tc,
                Ad=form.Ad,
                Soyad=form.Soyad,
                Tel=form.Tel,
                Email=form.Email,
                Adres=form.Adres,
                
            };

            Database.Session.Save(Musteri);
            Database.Session.Flush();
            return RedirectToAction("Index");
        }
        public ActionResult FirmaYeni()
        {
            return View(new MusterilerYeni() { });
        }
        [HttpPost]
        public ActionResult FirmaYeni(MusterilerYeni form)
        {
            if (!ModelState.IsValid)
            {
                return View(form);
            }

            var Musteri = new Musteri()
            {
                VergiNo = form.VergiNo,
                Ad = form.Ad,
                Soyad = form.Soyad,
                FirmaAdi = form.FirmaAdi,
                Tel = form.Tel,
                Email = form.Email,
                Adres = form.Adres,
            };

            Database.Session.Save(Musteri);
            Database.Session.Flush();

            return RedirectToAction("Index");
        }

        public ActionResult Duzenle(int id)
        {
            var musteriler = Database.Session.Load<Musteri>(id);
            if (musteriler==null)
            {
                return HttpNotFound();
            }
            return View(new MusterilerDuzenle() {
                Tc = musteriler.Tc,
                VergiNo = musteriler.VergiNo,
                Ad = musteriler.Ad,
                Soyad = musteriler.Soyad,
                FirmaAdi = musteriler.FirmaAdi,
                Tel = musteriler.Tel,
                Email = musteriler.Email,
                Adres = musteriler.Adres
            
            });
        }
        [HttpPost]
        public ActionResult Duzenle(int id,MusterilerDuzenle form)
        {
            var musteri = Database.Session.Load<Musteri>(id);
            if (musteri == null)
            {
                return HttpNotFound();
            }
            
            if (Database.Session.Query<Musteri>().Any(x=>x.Tc==form.Tc && x.Id!=id))
            {
                ModelState.AddModelError("Tc", "Tc kimlik numarası benzersiz olmalıdır.");
                return View(form);
            }
            if (Database.Session.Query<Musteri>().Any(x => x.VergiNo == form.VergiNo && x.Id != id))
            {
                ModelState.AddModelError("VergiNo", "Vergi numarası benzersiz olmalıdır.");
                return View(form);
            }

            musteri.Tc = form.Tc;
            musteri.VergiNo = form.VergiNo;
            musteri.Ad = form.Ad;
            musteri.Soyad = form.Soyad;
            musteri.FirmaAdi = form.FirmaAdi;
            musteri.Tel = form.Tel;
            musteri.Email = form.Email;
            musteri.Adres = form.Adres;


            Database.Session.Update(musteri);
            Database.Session.Flush();
            return RedirectToAction("Index");
        }

        public ActionResult CopeAt(int id)
        {
            var musteri = Database.Session.Load<Musteri>(id);
            if (musteri==null)
            {
                return HttpNotFound();
            }
            musteri.SilmeTarihi = DateTime.Now;

            Database.Session.Update(musteri);
            Database.Session.Flush();

            return RedirectToAction("Index");
        }
        public ActionResult Kurtar(int id)
        {
            var musteri = Database.Session.Load<Musteri>(id);
            if (musteri == null)
            {
                return HttpNotFound();
            }
            musteri.SilmeTarihi = null;

            Database.Session.Update(musteri);
            Database.Session.Flush();

            return RedirectToAction("Index");
        }
        public ActionResult Sil(int id)
        {
            var musteri = Database.Session.Load<Musteri>(id);
            if (musteri == null)
            {
                return HttpNotFound();
            }
            Database.Session.Delete(musteri);
            Database.Session.Flush();

            return RedirectToAction("index");
        }

         private const int PostPerPage=10;
        public ActionResult KasaIndex(int page=1,int id=0)
        {
            if (page<1)
            {
                return HttpNotFound();
            }
            var TotalCount=Database.Session.Query<CariHesap>().Count();

            var currentPage=Database.Session.Query<CariHesap>()
                .OrderByDescending(x=>x.Tarih)
                .Skip((page-1)*PostPerPage)
                .Take(PostPerPage).ToList();

            double giren = 0, cikan = 0;
            var carihesaplar = Database.Session.Query<CariHesap>().Where(x=>x.Musteri.Id==id).OrderByDescending(x=>x.Tarih);
          
            foreach (var item in carihesaplar)
            {
                giren = giren + item.GirilenMiktar;
                cikan = cikan + item.CikanMiktar;
            }
            var musteri = Database.Session.Load<Musteri>(id);
          //  var b = Database.Session.Query<Musteri>().Single(x => x.Id == id).Ad;
            
            return View(new KasaIndex()
            {
                CariHesap=new PagedData<CariHesap>(currentPage,TotalCount,page,PostPerPage),
                MusteriAdi=musteri.Ad,
                MusteriSoyadi=musteri.Soyad,
                GirenMiktar = giren,
                CikanMiktar = -cikan,
                KalanMiktar = giren - cikan,
                MusteriID = id,
               
            });
        }
        public ActionResult KasaYeni(int musteriId)
        {
            var musteri=Database.Session.Load<Musteri>(musteriId);;
            var turler=Database.Session.Query<Tur>();
            var odeme=Database.Session.Query<OdemeSekli>();
            ViewBag.TurID = new SelectList(turler, "Id", "Adi");
            ViewBag.OdemeID = new SelectList(odeme, "Id", "Adi");
            return View(new KasaYeni()
            {
                MusteriID=musteri.Id,
                MusteriAdi=musteri.Ad,
                MusteriSoyadi=musteri.Soyad,
                Tarih=DateTime.Now  
            });
        }
        [HttpPost]
        public ActionResult KasaYeni(int TurID,int OdemeID,int musteriId,KasaYeni form)
        {
            double  giren=0,cikan=0;
   
            var carihesap = new CariHesap();
            
 
            foreach (var item in  Database.Session.Query<CariHesap>().Where(x => x.Musteri.Id == musteriId))
            {
                giren = giren + item.GirilenMiktar;
                cikan = cikan + item.CikanMiktar;
            }

             carihesap.Tarih = form.Tarih;
             carihesap.Aciklama = form.Aciklama;
             carihesap.GirilenMiktar = form.GirilenMiktar;
             carihesap.CikanMiktar = form.CikanMiktar;

             carihesap.OdemeSekli = Database.Session.Load<OdemeSekli>(OdemeID);
             carihesap.Musteri =Database.Session.Load<Musteri>(musteriId);
             carihesap.Tur = Database.Session.Load<Tur>(TurID);

            if(carihesap.Tur.Id == 1 && carihesap.GirilenMiktar == 0)
            {
                return Redirect("KasaYeni?MusteriID=" + musteriId);
            }
            else if(carihesap.Tur.Id == 2 && carihesap.CikanMiktar == 0)
            {
                return Redirect("KasaYeni?MusteriID=" + musteriId);
            }

             Database.Session.Save(carihesap);
             Database.Session.Flush();
             return Redirect("KasaIndex?Id=" + musteriId);
        }

          public ActionResult KasaDuzenle(int id)
          {
              var carihesap = Database.Session.Load<CariHesap>(id);
              if(carihesap==null)
              {
                  return HttpNotFound();
              }   

CariTakip_30.05.2017/CariTakip/Views/Musteriler/Duzenle.cshtml
@model CariTakip.ViewModels.MusterilerDuzenle
<h1 style="text-align:center;color:#ffffff;">Müşteri Düzenleme</h1>
<hr />

    @using (Html.BeginForm())
    {
        <div class="form-group" style="color:red">
            @Html.ValidationSummary()
        </div>
        @if (Model.Tc.ToString() == null)
        {
            <div class="form-group">
                @Html.LabelFor(x => x.Tc, new { @style = "color:#ffffff" })
                @Html.TextBoxFor(x => x.Tc, new { @class = "form-control", @disabled = "true" })
            </div>
            <div class="form-group">
                @Html.LabelFor(x => x.VergiNo, new { @style = "color:#ffffff" })
                @Html.TextBoxFor(x => x.VergiNo, new { @class = "form-control",@required = "@required" })
            </div>
            <div class="form-group">
                @Html.LabelFor(x => x.Ad, new { @style = "color:#ffffff" })
                @Html.TextBoxFor(x => x.Ad, new { @class = "form-control", @required = "@required" })
            </div>
            <div class="form-group">
                @Html.LabelFor(x => x.Soyad, new { @style = "color:#ffffff" })
                @Html.TextBoxFor(x => x.Soyad, new { @class = "form-control", @required = "@required" })
            </div>
            <div class="form-group">
                @Html.LabelFor(x => x.FirmaAdi, new { @style = "color:#ffffff" })
                @Html.TextBoxFor(x => x.FirmaAdi, new { @class = "form-control",@required = "@required" })
            </div>
            <div class="form-group">
                @Html.LabelFor(x => x.Tel, new { @style = "color:#ffffff" })
                @Html.TextBoxFor(x => x.Tel, new { @class = "form-control", @required = "@required" })
            </div>
            <div class="form-group">
                @Html.LabelFor(x => x.Email, new { @style = "color:#ffffff" })
                @Html.TextBoxFor(x => x.Email, new { @class = "form-control", type = "email", @required = "@required" })
            </div>
            <div class="form-group">
                @Html.LabelFor(x => x.Adres, new { @style = "color:#ffffff" })
                @Html.TextBoxFor(x => x.Adres, new { @class = "form-control", @required = "@required" })
            </div>
        }
        else if (Model.Tc != null)
        {
            <div class="form-group">
                @Html.LabelFor(x => x.Tc, new { @style = "color:#ffffff" })
                @Html.TextBoxFor(x => x.Tc, new { @class = "form-control", @required = "@required" })
            </div>
            <div class="form-group">
                @Html.LabelFor(x => x.VergiNo, new { @style = "color:#ffffff" })
                @Html.TextBoxFor(x => x.VergiNo, new { @class = "form-control", @disabled = "true" })
            </div>
            <div class="form-group">
                @Html.LabelFor(x => x.Ad, new { @style = "color:#ffffff" })
                @Html.TextBoxFor(x => x.Ad, new { @class = "form-control", @required = "@required" })
            </div>
            <div class="form-group">
                @Html.LabelFor(x => x.Soyad, new { @style = "color:#ffffff" })
                @Html.TextBoxFor(x => x.Soyad, new { @class = "form-control", @required = "@required" })
            </div>
            <div class="form-group">
                @Html.LabelFor(x => x.FirmaAdi, new { @style = "color:#ffffff" })
                @Html.TextBoxFor(x => x.FirmaAdi, new { @class = "form-control", @disabled = "true" })
            </div>
            <div class="form-group">
                @Html.LabelFor(x => x.Tel, new { @style = "color:#ffffff" })
                @Html.TextBoxFor(x => x.Tel, new { @class = "form-control", @required = "@required" })
            </div>
            <div class="form-group">
                @Html.LabelFor(x => x.Email, new { @style = "color:#ffffff" })
                @Html.TextBoxFor(x => x.Email, new { @class = "form-control", type = "email", @required = "@required" })
            </div>
            <div class="form-group">
                @Html.LabelFor(x => x.Adres, new { @style = "color:#ffffff" })
                @Html.TextBoxFor(x => x.Adres, new { @class = "form-control", @required = "@required" })
            </div>
        }
        <hr />
        <div class="form-group">
            <input type="submit" value="Düzenle" class="btn btn-success" />
            <a href="@Url.Action("Index")" class="btn btn-primary pull-right">
                Geri Dön
            </a>
        </div>
    }

CariTakip_30.05.2017/CariTakip/Views/Musteriler/FirmaYeni.cshtml
@model CariTakip.ViewModels.MusterilerYeni
<h1 style="text-align:center;color:#ffffff;">Yeni Müşteri Ekleme</h1>
<hr />
@using (Html.BeginForm())
{
    @Html.ValidationSummary()

    <hr />
        <div class="form-group">
            @Html.LabelFor(x => x.VergiNo, new { @style = "color:#ffffff" })
            @Html.TextBoxFor(x => x.VergiNo, new { @class = "form-control", @required = "@required" })
        </div>
        <div class="form-group">
            @Html.LabelFor(x => x.Ad, new { @style = "color:#ffffff" })
            @Html.TextBoxFor(x => x.Ad, new { @class = "form-control", @required = "@required" })
        </div>
        <div class="form-group">
            @Html.LabelFor(x => x.Soyad, new { @style = "color:#ffffff" })
            @Html.TextBoxFor(x => x.Soyad, new { @class = "form-control", @required = "@required" })
        </div>
        <div class="form-group">
            @Html.LabelFor(x => x.FirmaAdi, new { @style = "color:#ffffff" })
            @Html.TextBoxFor(x => x.FirmaAdi, new { @class = "form-control", @required = "@required" })
        </div>
        <div class="form-group">
            @Html.LabelFor(x => x.Tel, new { @style = "color:#ffffff" })
            @Html.TextBoxFor(x => x.Tel, new { @class = "form-control", @required = "@required" })
        </div>
        <div class="form-group">
            @Html.LabelFor(x => x.Email, new { @style = "color:#ffffff" })
            @Html.TextBoxFor(x => x.Email, new { @class = "form-control", type = "email", @required = "@required" })
        </div>
        <div class="form-group">
            @Html.LabelFor(x => x.Adres, new { @style = "color:#ffffff" })
            @Html.TextBoxFor(x => x.Adres, new { @class = "form-control", @required = "@required" })
        </div>
        <hr />
        <div class="form-group">
            <input type="submit" value="Muşteri Oluştur" class="btn btn-success" />

            <a href="@Url.Action("Index")" class="btn btn-primary pull-right">
                Geri Dön
            </a>


        </div>
}

CariTakip_30.05.2017/CariTakip/Views/Musteriler/KasaDuzenle.cshtml
@model CariTakip.ViewModels.KasaDuzenle

<h1 style="text-align:center;color:#ffffff;">Kasa Düzenle: @Model.MusteriAdi @Model.MusteriSoyadi </h1>



    @using (Html.BeginForm("KasaDuzenle", "Musteri", FormMethod.Post))
    {
     

        <div class="form-group">
            @Html.Label("Tarih", new { @style = "color:#ffffff" })
            @Html.TextBoxFor(x => x.Tarih, new { @class = "form-control", @required = "required" })
        </div>
        <div class="form-group">
            @Html.Label("Açıklama", new { @style = "color:#ffffff" })
            @Html.TextBoxFor(x => x.Aciklama, new { @class = "form-control", @required = "required" })
        </div>
        <div class="form-group">
            @Html.Label("Borç", new { @style = "color:#ffffff" })
            @Html.TextBoxFor(x => x.GirilenMiktar, new { @class = "form-control", @required = "required" })
        </div>
        <div class="form-group">
            @Html.Label("Alacak", new { @style = "color:#ffffff" })
            @Html.TextBoxFor(x => x.CikanMiktar, new { @class = "form-control", @required = "required" })
        </div>


        <div class="form-group">
            @Html.Label("Tür", new { @style = "color:#ffffff" })
            @Html.DropDownList("TurID", ViewBag.TurID as SelectList, new { @class = "form-control" })
        </div>
        <div class="form-group">
            @Html.Label("Ödeme Şekli", new { @style = "color:#ffffff" })
            @Html.DropDownList("OdemeID", ViewBag.OdemeID as SelectList, new { @class = "form-control" })
        </div>


        <div class="form-group">
            <input type="submit" value="Duzenle" class="btn btn-warning" />
            <a href="@Url.Action("KasaIndex", "Musteriler", new {Id=Model.MusteriID})" class="btn btn-primary pull-right">Geri Dön</a>
        </div>
    }

CariTakip_30.05.2017/CariTakip/Views/Musteriler/KasaIndex.cshtml
@model CariTakip.ViewModels.KasaIndex
<h1 style="text-align:center;color:#ffffff;">Kasa Oluştur: @Model.MusteriAdi @Model.MusteriSoyadi  </h1>

<hr/>
<div class="btn-group pull-right">


    @if (Model.CariHesap.HasPreviousPage)
    {
        <a href="@Url.Action("KasaIndex", new { page = Model.CariHesap.PreviousPage(), Id = Model.MusteriID })" class="btn btn-default btn-sm"><i class="glyphicon glyphicon-chevron-left"></i>Önceki Sayfa</a>
    }
    else
    {

        <a href="#" class="btn btn-default btn-sm disabled">
            <i class="glyphicon glyphicon-chevron-left"></i>Önceki Sayfa
        </a>
    }
    @if (Model.CariHesap.HasNextPage)
    {
        <a href="@Url.Action("KasaIndex", new { page = Model.CariHesap.NextPage(),Id=Model.MusteriID })" class="btn btn-default btn-sm">
            <i class="glyphicon glyphicon-chevron-right"></i> Sonraki Sayfa
        </a>
    }
    else
    {
        <a href="#" class="btn btn-default btn-sm disabled">
            <i class="glyphicon glyphicon-chevron-right disabled"></i> Sonraki Sayfa
        </a>
    }
</div>



    <div class="btn btn-toolbar">
        <a href="@Url.Action("KasaYeni", "Musteriler", new { Model.MusteriID })" class=" btn btn-primary btn-sm"><i class="glyphicon glyphicon-plus"></i> Yeni Cari Ekle</a>
    </div>
    <table class="table table-striped">
        <thead>
            <tr style="color: #ffffff;" >
             
                <th>Tarih</th>
                <th>Saat</th>
                <th>Aciklama</th>
                <th>Borç</th>
                <th>Alacak</th>
                <th>Türü</th>
                <th>Ödeme Şekli</th>
                <th>İşlemler</th>
            </tr>
        </thead>
        <tbody>

            @foreach (var carihesap in Model.CariHesap)
            {
                <tr style="color: #cbae48">
                   
                    <td>@carihesap.Tarih.ToString("MM/dd/yyyy")</td>
                    <td>@carihesap.Tarih.ToString("HH: mm :ss")</td>
                    <td>@carihesap.Aciklama</td>
                    <td>@carihesap.GirilenMiktar</td>
                    <td>@carihesap.CikanMiktar</td>
                 
                    <td>@carihesap.Tur.Adi</td>
                    <td>@carihesap.OdemeSekli.Adi</td>
                    <td>
                        <div class="dropdown">
                            <button class="btn btn-warning btn-xs dropdown-toggle" type="button" data-toggle="dropdown">
                                İşlem Seç
                                <span class="caret"></span>
                            </button>
                            <ul class="dropdown-menu">

                                <li><a href="@Url.Action("KasaDuzenle", "Musteriler", new { carihesap.Id })">Düzenle</a></li>
                                <li><a href="@Url.Action("KasaSil", "Musteriler", new { carihesap.Id })" data-post="@carihesap.Tarih Kayıtı silmek istiyor musunuz? ">Sil</a></li>
                                
                            </ul>
                        </div>
                    </td>
                </tr>
            }

        </tbody>
    </table>
<hr />

  
    <a href="@Url.Action("KasaExcellCikart", "Musteriler", new { Model.MusteriID })" class="btn btn-default"><i class="glyphicon glyphicon-export"></i>Excel'e Çıkart</a>
    <div class="btn-group pull-right">
        <div class="panel panel-default">
            <div class="panel-heading">Sonuç</div>
            <div class="panel-body" style="background-color:rgba(240, 179, 93, 0.90)">

                <div class="form-group">


                    Borç : @Model.GirenMiktar   <br />  Alacak :@Model.CikanMiktar<br />
                    @if (Model.GirenMiktar > Math.Abs(Model.CikanMiktar))
                    {
                        <b>Kalan Borç:</b> @Model.KalanMiktar
                    }
                    else
                    {
                        <b>Kalan Alacak:</b> @Model.KalanMiktar
                    }
                </div>
            </div>

        </div>
    
    </div>

CariTakip_30.05.2017/CariTakip/Views/Musteriler/KasaYeni.cshtml
    @model CariTakip.ViewModels.KasaYeni

    <h1 style="text-align:center;color:#ffffff;">Yeni Kasa Oluştur: @Model.MusteriAdi @Model.MusteriSoyadi </h1>


    @using (Html.BeginForm("KasaYeni","Musteri",FormMethod.Post))
        {
            @Html.ValidationSummary(true)
        
            <div class="form-group">
                 @Html.Label("Tarih", new { @style = "color:#ffffff" })
                 @Html.TextBoxFor(x => x.Tarih, new { @class = "form-control",@required="required" })
            </div>
            <div class="form-group">
                @Html.Label("Açıklama", new { @style = "color:#ffffff" })
                @Html.TextBoxFor(x => x.Aciklama, new { @class = "form-control", @required = "required" })
            </div>
              <div class="form-group">
               @Html.Label("Ödeme Şekli", new { @style = "color:#ffffff" })
               @Html.DropDownList("OdemeID", ViewBag.OdemeID as SelectList, new { @class = "form-control" })
            </div>
               <div class="form-group"> 
                @Html.Label("Tür", new { @style = "color:#ffffff" })
                @Html.DropDownList("TurID", ViewBag.TurID as SelectList, new { @class = "form-control" })
              
           </div>
           
            
            <div class="form-group">
                @Html.Label("Borç", new { @style = "color:#ffffff" })
                @Html.TextBoxFor(x => x.GirilenMiktar, new { @class = "form-control", @required = "required" })
            </div>
            <div class="form-group">
                @Html.Label("Alacak", new { @style = "color:#ffffff" })
                @Html.TextBoxFor(x => x.CikanMiktar, new { @class = "form-control", @required = "required" })
            </div>
        
    
            <div class="form-group">
                <input type="submit" value="Kaydet" class="btn btn-warning"/>
                <a href="@Url.Action("KasaIndex", "Musteriler", new {Id=Model.MusteriID})" class="btn btn-primary pull-right">Geri Dön</a>
            </div>
 }
<hr />
<ul style="color:white">
    <li>
        Eğer tür olarak BORÇ seçiliyse Borç alanı doldurulması zorunludur.
    </li>
    <li>
        Eğer tür olarak AlACAK seçiliyse Alacak alanı doldurulması zorunludur.
    </li>
</ul>